# Generated by Django 5.0.14 on 2026-03-12 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipo de imóvel',
                'verbose_name_plural': 'tipos de imóvel',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_anuncio', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel')], default='venda', max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('area_m2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Área (m²)')),
                ('quartos', models.PositiveSmallIntegerField(default=0)),
                ('banheiros', models.PositiveSmallIntegerField(default=0)),
                ('vagas', models.PositiveSmallIntegerField(default=0, verbose_name='Vagas garagem')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anunciante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_anunciados', to=settings.AUTH_USER_MODEL)),
                ('tipo_imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis', to='properties.propertytype')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/%Y/%m/')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('legenda', models.CharField(blank=True, max_length=100)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='properties.property')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
