# Generated by Django 5.0.14 on 2026-03-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
